@Library('ansible-shared-library') _

node {

    stage('Load Configuration') {

        def config = readProperties file: 'Assignment-6/config/config.properties'

        ansiblePipeline(
            SLACK_CHANNEL_NAME: config.SLACK_CHANNEL_NAME,
            ENVIRONMENT: config.ENVIRONMENT,
            CODE_BASE_PATH: config.CODE_BASE_PATH,
            ACTION_MESSAGE: config.ACTION_MESSAGE,
            KEEP_APPROVAL_STAGE: config.KEEP_APPROVAL_STAGE
        )
    }
}
