@Library('ansible-shared-library') _

node {

    stage('Clone') {
        echo 'Cloning project repository'
        checkout scm
    }

    stage('Load Configuration') {

        def configFile = readFile('Assignment-6/config/config.properties')
        def config = [:]

        configFile.split('\n').each { line ->
            line = line.trim()

            if (line && !line.startsWith('#') && line.contains('=')) {
                def parts = line.split('=', 2)
                config[parts[0].trim()] = parts[1].trim()
            }
        }

        ansiblePipeline(
            SLACK_CHANNEL_NAME: config['SLACK_CHANNEL_NAME'],
            ENVIRONMENT: config['ENVIRONMENT'],
            CODE_BASE_PATH: config['CODE_BASE_PATH'],
            ACTION_MESSAGE: config['ACTION_MESSAGE'],
            KEEP_APPROVAL_STAGE: config['KEEP_APPROVAL_STAGE']
        )
    }
}
